#%RAML 1.0 Trait
headers:
  clientId:
    type: string
    required: true
    example: "we5fsdfsdf4545sd4f86ss7sd"
  clientSecret:
    type: string
    required: true
    example: "sf54ddv6df4v54d86fv4d1vdf4fvv6v"