#%RAML 1.0 Trait
body:
  application/json:
    example: 
      [
        {
          "EmpId": 1003261,
          "Name": "Revanth Reddy Penugonda",
          "EmpUserName": "PREDDY",
          "Gender": "Male",
          "DOB": "25-10-1995",
          "MaritalStatus": "UnMarried",
          "SpouseName": "PonkMuia",
          "SpouseAge": 25,
          "ChildName": "PapsvaTi",
          "Address": "2/190-A, K.K.Street",
          "Village": "Duvvur",
          "District": "Kadapa",
          "State": "Andhra Pradesh",
          "Country": "India",
          "PinCode": 516175,
          "Email": "revanth@gmail.com",
          "PhNo": 8142602737,
          "JoinedDate": "06/09/2021",
          "CompanyEmail": "penugonda.reddy@insite360suite.com",
          "Status": "Active"
        }
      ]